# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr4.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nasr4.proto\x12\x12\x61sr4.recognizer.v1"X\n\x10RecognizeRequest\x12\x35\n\x06\x63onfig\x18\x01 \x01(\x0b\x32%.asr4.recognizer.v1.RecognitionConfig\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c"\x8d\x01\n\x11RecognitionConfig\x12=\n\nparameters\x18\x01 \x01(\x0b\x32).asr4.recognizer.v1.RecognitionParameters\x12\x39\n\x08resource\x18\x02 \x01(\x0b\x32\'.asr4.recognizer.v1.RecognitionResource"A\n\x15RecognitionParameters\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\r"i\n\x13RecognitionResource\x12<\n\x05topic\x18\x01 \x01(\x0e\x32-.asr4.recognizer.v1.RecognitionResource.Model"\x14\n\x05Model\x12\x0b\n\x07GENERIC\x10\x00"!\n\x11RecognizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2f\n\nRecognizer\x12X\n\tRecognize\x12$.asr4.recognizer.v1.RecognizeRequest\x1a%.asr4.recognizer.v1.RecognizeResponseb\x06proto3'
)


_RECOGNIZEREQUEST = DESCRIPTOR.message_types_by_name["RecognizeRequest"]
_RECOGNITIONCONFIG = DESCRIPTOR.message_types_by_name["RecognitionConfig"]
_RECOGNITIONPARAMETERS = DESCRIPTOR.message_types_by_name["RecognitionParameters"]
_RECOGNITIONRESOURCE = DESCRIPTOR.message_types_by_name["RecognitionResource"]
_RECOGNIZERESPONSE = DESCRIPTOR.message_types_by_name["RecognizeResponse"]
_RECOGNITIONRESOURCE_MODEL = _RECOGNITIONRESOURCE.enum_types_by_name["Model"]
RecognizeRequest = _reflection.GeneratedProtocolMessageType(
    "RecognizeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOGNIZEREQUEST,
        "__module__": "asr4_pb2"
        # @@protoc_insertion_point(class_scope:asr4.recognizer.v1.RecognizeRequest)
    },
)
_sym_db.RegisterMessage(RecognizeRequest)

RecognitionConfig = _reflection.GeneratedProtocolMessageType(
    "RecognitionConfig",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOGNITIONCONFIG,
        "__module__": "asr4_pb2"
        # @@protoc_insertion_point(class_scope:asr4.recognizer.v1.RecognitionConfig)
    },
)
_sym_db.RegisterMessage(RecognitionConfig)

RecognitionParameters = _reflection.GeneratedProtocolMessageType(
    "RecognitionParameters",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOGNITIONPARAMETERS,
        "__module__": "asr4_pb2"
        # @@protoc_insertion_point(class_scope:asr4.recognizer.v1.RecognitionParameters)
    },
)
_sym_db.RegisterMessage(RecognitionParameters)

RecognitionResource = _reflection.GeneratedProtocolMessageType(
    "RecognitionResource",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOGNITIONRESOURCE,
        "__module__": "asr4_pb2"
        # @@protoc_insertion_point(class_scope:asr4.recognizer.v1.RecognitionResource)
    },
)
_sym_db.RegisterMessage(RecognitionResource)

RecognizeResponse = _reflection.GeneratedProtocolMessageType(
    "RecognizeResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOGNIZERESPONSE,
        "__module__": "asr4_pb2"
        # @@protoc_insertion_point(class_scope:asr4.recognizer.v1.RecognizeResponse)
    },
)
_sym_db.RegisterMessage(RecognizeResponse)

_RECOGNIZER = DESCRIPTOR.services_by_name["Recognizer"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RECOGNIZEREQUEST._serialized_start = 34
    _RECOGNIZEREQUEST._serialized_end = 122
    _RECOGNITIONCONFIG._serialized_start = 125
    _RECOGNITIONCONFIG._serialized_end = 266
    _RECOGNITIONPARAMETERS._serialized_start = 268
    _RECOGNITIONPARAMETERS._serialized_end = 333
    _RECOGNITIONRESOURCE._serialized_start = 335
    _RECOGNITIONRESOURCE._serialized_end = 440
    _RECOGNITIONRESOURCE_MODEL._serialized_start = 420
    _RECOGNITIONRESOURCE_MODEL._serialized_end = 440
    _RECOGNIZERESPONSE._serialized_start = 442
    _RECOGNIZERESPONSE._serialized_end = 475
    _RECOGNIZER._serialized_start = 477
    _RECOGNIZER._serialized_end = 579
# @@protoc_insertion_point(module_scope)
