FROM docker.registry.verbio.com/engineering/devops/debian10-intel-oneapi-python:3.7

# Install CUDA 11.7.0

RUN apt-get update && apt-get install libxml2 zstd -y

RUN wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run && \
    sh cuda_11.7.0_515.43.04_linux.run --silent --toolkit && \
    rm -rf cuda_11.7.0_515.43.04_linux.run

RUN mkdir cudnn && \
    cd cudnn && \
    wget https://europe.mirror.pkgbuild.com/community/os/x86_64/cudnn-8.6.0.163-1-x86_64.pkg.tar.zst && \
    tar --use-compress-program=unzstd -xvf cudnn-8.6.0.163-1-x86_64.pkg.tar.zst && \
    mv usr/include/* /usr/local/cuda/include/ && \
    mv usr/lib/* /usr/local/cuda/lib64/ && \
    cd .. && \
    rm -rf cudnn

COPY TensorRT-8.5.1.7.Linux.x86_64-gnu.cuda-11.8.cudnn8.6.tar.gz /

RUN . /opt/intel/oneapi/setvars.sh && \
    tar xzvf TensorRT-8.5.1.7.Linux.x86_64-gnu.cuda-11.8.cudnn8.6.tar.gz && \
    python -m pip install TensorRT-8.5.1.7/python/tensorrt-8.5.1.7-cp37-none-linux_x86_64.whl && \
    mv TensorRT-8.5.1.7/targets/x86_64-linux-gnu/bin/* /bin/ && \
    mv TensorRT-8.5.1.7/targets/x86_64-linux-gnu/lib/* /usr/lib/x86_64-linux-gnu/ && \
    mv TensorRT-8.5.1.7/targets/x86_64-linux-gnu/include/Nv* /usr/local/include/ && \
    rm -rf TensorRT-8.5.1.7 TensorRT-8.5.1.7.Linux.x86_64-gnu.cuda-11.8.cudnn8.6.tar.gz

RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV CUDACXX=/usr/local/cuda/bin/nvcc


