name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. 
          flake8 . --count --exit-zero --max-complexity=10  --statistics
      - name: gRPC code generation
        run: |
          cd scripts
          ./generate_grpc_code.sh
          cd ..
      - name: Unit tests
        run: |
          cd test
          python3 -m pytest
          cd ..
      - name: Execute client help
        run: |
          cd scripts
          ./generate_grpc_code.sh
          cd ../cli-client
          ./recognizer_stream.py --help
          ./synthesizer_stream.py --help
